name: 🇫🇷

on: 
  - push
  - delete

jobs:
  mirror_gitlab:
    name: 🪞 Gitlab
    runs-on: ubuntu-latest
    steps:
    - uses: SocialGouv/actions/mirror-gitlab@master
      with:
        project: SocialGouv/sample-next-app/sample-next-app
        token: ${{ secrets.SOCIALGROOVYBOT_GITLAB_TOKEN }}
