name: Production

on:
  push:
    tags:
      - v*

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  ##############################################################################
  ## BUILD AND REGISTER DOCKER IMAGE
  ##############################################################################
  register:
    name: Build & Register docker images
    runs-on: ubuntu-latest
    steps:
      - name: Get project name
        run: |
          echo "project=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Application
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          project: ${{ env.project }}
          imageName: ${{ env.project }}/app
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Hasura
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          dockercontext: ./hasura
          project: ${{ env.project }}
          dockerfile: ./hasura/Dockerfile
          token: ${{ secrets.GITHUB_TOKEN }}
          imageName: ${{ env.project }}/hasura

  ##############################################################################
  ## DEPLOY PRODUCTION APPLICATION
  ##############################################################################
  deploy-prod:
    name: Deploy production
    runs-on: ubuntu-latest
    needs: [register]
    environment:
      name: production
      url: https://sample-next-app.fabrique.social.gouv.fr
    steps:
      - name: Use k8s manifests generation
        uses: SocialGouv/actions/autodevops-manifests@v1
        with:
          environment: "prod"
          rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
          socialgouvBaseDomain: ${{ secrets.SOCIALGOUV_BASE_DOMAIN }}
          pgUserSecretPrefix: pg-user

      - name: Use autodevops deployment
        uses: SocialGouv/actions/autodevops-deploy@v1
        with:
          environment: "prod"
          token: ${{ secrets.GITHUB_TOKEN }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
